import {createContext,useContext,useEffect,useMemo,useState,ReactNode} from 'react';
import {AppState,initialState,now,uid,Profile,Area,Habit,Objective,ObjectiveItem,Consumption,Meal,WaterLog,Workout,Income,Expense,Budget,FinancialGoal,FrequentAction,Reminder,dateKey} from '../domain/types';
import {loadState,saveState,exportState,clearState,clearAuthCache} from '../db/localDb';
import {calculateScore} from '../domain/score';
import {enqueueDiff} from '../sync/outbox';
import {supabase,supabaseConfigured} from '../lib/supabase';
import {syncState} from '../sync/sync';
import {signOut as authSignOut} from '../auth/authService';
import {scheduleReminder} from '../notifications/notifications';

type SyncStatus='offline'|'synced'|'syncing'|'error'|'not-configured';
type Ctx={state:AppState;loading:boolean;authReady:boolean;authUser:any;syncStatus:SyncStatus;update:(fn:(s:AppState)=>AppState)=>void;syncNow:()=>Promise<void>;signOut:()=>Promise<void>;addArea:(x:Omit<Area,'id'|'createdAt'|'updatedAt'>)=>void;addHabit:(x:Omit<Habit,'id'|'createdAt'|'updatedAt'>)=>void;logHabit:(id:string,value:number,note?:string)=>void;addObjective:(x:Omit<Objective,'id'|'createdAt'|'updatedAt'|'progress'>)=>void;addItem:(x:Omit<ObjectiveItem,'id'|'createdAt'|'updatedAt'>)=>void;addConsumption:(x:Omit<Consumption,'id'|'createdAt'|'updatedAt'>)=>void;logConsumption:(id:string,qty:number)=>void;addMeal:(x:Omit<Meal,'id'|'createdAt'|'updatedAt'>)=>void;addWater:(ml:number)=>void;addWorkout:(x:Omit<Workout,'id'|'createdAt'|'updatedAt'|'syncState'>)=>void;addIncome:(x:Omit<Income,'id'|'createdAt'|'updatedAt'|'syncState'>)=>void;addExpense:(x:Omit<Expense,'id'|'createdAt'|'updatedAt'|'syncState'>)=>void;addBudget:(x:Omit<Budget,'id'|'createdAt'|'updatedAt'>)=>void;addFinancialGoal:(x:Omit<FinancialGoal,'id'|'createdAt'|'updatedAt'>)=>void;addReminder:(x:Omit<Reminder,'id'|'createdAt'|'updatedAt'>)=>void;saveFrequent:(x:Omit<FrequentAction,'id'|'createdAt'|'updatedAt'>)=>void;setProfile:(p:Omit<Profile,'id'|'createdAt'|'updatedAt'>)=>void;reorderTabs:(tabs:string[])=>void;toggleHome:(m:string)=>void;doExport:()=>void;reset:()=>void;score:ReturnType<typeof calculateScore>};
const AppCtx=createContext<Ctx|null>(null);

export function AppProvider({children}:{children:ReactNode}){
 const [state,setState]=useState<AppState>(initialState()); const [loading,setLoading]=useState(true); const [authReady,setAuthReady]=useState(!supabaseConfigured); const [authUser,setAuthUser]=useState<any>(null); const [syncStatus,setSyncStatus]=useState<SyncStatus>(supabaseConfigured?'offline':'not-configured');
 useEffect(()=>{let alive=true; loadState().then(s=>{if(alive){setState(s);setLoading(false)}}); if(!supabase) return; supabase.auth.getSession().then(({data})=>{if(!alive)return;setAuthUser(data.session?.user??null);setAuthReady(true)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setAuthUser(session?.user??null);setAuthReady(true)}); return()=>{alive=false;subscription.unsubscribe()};},[]);
 useEffect(()=>{if(!loading) saveState(state)},[state,loading]);
 useEffect(()=>{if(!supabaseConfigured||!authUser||loading)return; syncNow().catch(()=>{});},[authUser?.id,loading]);
 useEffect(()=>{const online=()=>{if(authUser)syncNow().catch(()=>{})}; window.addEventListener('online',online); return()=>window.removeEventListener('online',online)},[authUser?.id]);
 useEffect(()=>{if(!authUser||!supabaseConfigured)return; const timer=window.setInterval(()=>syncNow().catch(()=>{}),10000); return()=>window.clearInterval(timer)},[authUser?.id,state]);
 const update=(fn:(s:AppState)=>AppState)=>setState(prev=>{const next=fn(structuredClone(prev)); enqueueDiff(prev,next).catch(()=>{}); return next});
 const stamp=(x:any)=>({...x,id:uid(),createdAt:now(),updatedAt:now()});
 const addArea=(x:any)=>update(s=>({...s,areas:[...s.areas,stamp(x)]})); const addHabit=(x:any)=>update(s=>({...s,habits:[...s.habits,stamp(x)]})); const logHabit=(id:string,value:number,note?:string)=>update(s=>({...s,habitLogs:[...s.habitLogs,stamp({habitId:id,date:dateKey(),value,note,origin:'manual',syncState:'pending'})]}));
 const addObjective=(x:any)=>update(s=>({...s,objectives:[...s.objectives,stamp({...x,progress:0})]})); const addItem=(x:any)=>update(s=>({...s,objectiveItems:[...s.objectiveItems,stamp(x)]})); const addConsumption=(x:any)=>update(s=>({...s,consumptions:[...s.consumptions,stamp(x)]})); const logConsumption=(id:string,qty:number)=>update(s=>({...s,consumptionLogs:[...s.consumptionLogs,stamp({consumptionId:id,quantity:qty,date:dateKey(),syncState:'pending'})]}));
 const addMeal=(x:any)=>update(s=>({...s,meals:[...s.meals,stamp({...x,date:x.date||dateKey(),syncState:'pending'})]})); const addWater=(ml:number)=>update(s=>({...s,waterLogs:[...s.waterLogs,stamp({amountMl:ml,date:dateKey(),syncState:'pending'})]})); const addWorkout=(x:any)=>update(s=>({...s,workouts:[...s.workouts,stamp({...x,date:x.date||dateKey(),syncState:'pending'})]})); const addIncome=(x:any)=>update(s=>({...s,incomes:[...s.incomes,stamp({...x,date:x.date||dateKey(),syncState:'pending'})]})); const addExpense=(x:any)=>update(s=>({...s,expenses:[...s.expenses,stamp({...x,date:x.date||dateKey(),syncState:'pending'})]})); const addBudget=(x:any)=>update(s=>({...s,budgets:[...s.budgets,stamp(x)]})); const addFinancialGoal=(x:any)=>update(s=>({...s,financialGoals:[...s.financialGoals,stamp(x)]})); const addReminder=(x:any)=>{const r=stamp(x);update(s=>({...s,reminders:[...s.reminders,r]}));scheduleReminder(r).catch(()=>{})}; const saveFrequent=(x:any)=>update(s=>{const existing=s.frequentActions.find(a=>a.domain===x.domain&&a.label===x.label&&a.payload===x.payload);if(existing)return {...s,frequentActions:s.frequentActions.map(a=>a.id===existing.id?{...a,uses:a.uses+1,updatedAt:now()}:a)};return {...s,frequentActions:[...s.frequentActions,stamp(x)]}});
 const setProfile=(p:any)=>update(s=>{const id=authUser?.id||p.id||uid(); const profile={...p,id,createdAt:p.createdAt||now(),updatedAt:now()}; const areas=s.areas.length?s.areas:[stamp({name:'Ejercicio',icon:'🏃',active:true,order:0,isCustom:false}),stamp({name:'Alimentación',icon:'🍽️',active:true,order:1,isCustom:false}),stamp({name:'Finanzas',icon:'💳',active:true,order:2,isCustom:false}),stamp({name:'Vicios',icon:'🔥',active:true,order:3,isCustom:false})]; const consumptions=s.consumptions.length?s.consumptions:[stamp({name:'Tabaco',unit:'cigarrillos',active:true}),stamp({name:'Cannabis',unit:'unidades',active:true}),stamp({name:'Alcohol',unit:'unidades',active:true})]; return {...s,profile,areas,consumptions}});
 const reorderTabs=(tabs:string[])=>update(s=>({...s,nav:{...s.nav,tabs}})); const toggleHome=(m:string)=>update(s=>({...s,home:{modules:s.home.modules.includes(m)?s.home.modules.filter(x=>x!==m):[...s.home.modules,m]}})); const reset=()=>{clearState();clearAuthCache();setState(initialState())}; const doExport=()=>exportState(state);
 const syncNow=async()=>{if(!supabase||!authUser||!navigator.onLine){setSyncStatus('offline');return} setSyncStatus('syncing'); try{const last=localStorage.getItem('impulse.lastSync')||undefined;const result=await syncState(state,authUser.id,last);if(result.ok){setState(result.state);localStorage.setItem('impulse.lastSync',result.serverTime);setSyncStatus('synced')}}catch(e){console.error(e);setSyncStatus('error')}};
 const signOut=async()=>{await authSignOut();setAuthUser(null);setState(initialState());localStorage.removeItem('impulse.lastSync')}; const score=useMemo(()=>calculateScore(state),[state]);
 return <AppCtx.Provider value={{state,loading,authReady,authUser,syncStatus,update,syncNow,signOut,addArea,addHabit,logHabit,addObjective,addItem,addConsumption,logConsumption,addMeal,addWater,addWorkout,addIncome,addExpense,addBudget,addFinancialGoal,addReminder,saveFrequent,setProfile,reorderTabs,toggleHome,doExport,reset,score}}>{children}</AppCtx.Provider>
}
export const useApp=()=>{const c=useContext(AppCtx);if(!c)throw Error('useApp fuera de AppProvider');return c};
