import {useEffect,useState} from 'react';
import {getPersona,savePersona,getProactiveSettings,saveProactiveSettings,getProactiveEvents,generateProactive,dismissProactive,getMealPlans,createMealPlan,completeMealItem} from '../phase5Service';
import {initializeRevenueCat,refreshSubscriptionFromStore} from '../billing/revenueCat';
import {useApp} from '../hooks/useApp';
const personas:any={balanced:'Equilibrado',friend:'Amiga/o',coach:'Entrenador',mentor:'Mentor',direct:'Directo',motivator:'Motivador',analytical:'Analítico',professional:'Profesional'};
export function Phase5Panel({close}:{close:()=>void}){const {authUser}=useApp();const [tab,setTab]=useState('ia');const [persona,setPersona]=useState<any>({persona:'balanced',intensity:3});const [pro,setPro]=useState<any>(null);const [events,setEvents]=useState<any[]>([]);const [plans,setPlans]=useState<any[]>([]);const [busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{setPersona(await getPersona());setPro(await getProactiveSettings());setEvents(await getProactiveEvents());setPlans(await getMealPlans());if(authUser)await initializeRevenueCat(authUser.id)})()},[authUser?.id]);
 const refresh=async()=>{setBusy(true);try{await generateProactive();setEvents(await getProactiveEvents())}finally{setBusy(false)}};
 const makePlan=async()=>{setBusy(true);try{const start=new Date();const end=new Date(start);end.setDate(end.getDate()+6);const days=['Desayuno','Almuerzo','Cena'];await createMealPlan({name:'Plan semanal Impulse',start_date:start.toISOString().slice(0,10),end_date:end.toISOString().slice(0,10),target_notes:'Plan simple y adaptable',status:'active'},Array.from({length:7*3},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+Math.floor(i/3));return {date:d.toISOString().slice(0,10),meal_type:['breakfast','lunch','dinner'][i%3],title:`${days[i%3]} — opción simple`,description:'Podés reemplazarlo según tus preferencias.',servings:1}}));setPlans(await getMealPlans())}finally{setBusy(false)}};
 return <div className="overlay bottom"><div className="sheet phase4Sheet"><div className="grab"/><div className="sheetHead"><div><span className="eyebrow">FASE 5</span><h2>Impulse inteligente</h2></div><button className="iconbtn" onClick={close}>×</button></div><div className="tabs"><button className={tab==='ia'?'active':''} onClick={()=>setTab('ia')}>IA proactiva</button><button className={tab==='food'?'active':''} onClick={()=>setTab('food')}>Plan de comidas</button><button className={tab==='game'?'active':''} onClick={()=>setTab('game')}>Progreso</button><button className={tab==='premium'?'active':''} onClick={()=>setTab('premium')}>Premium</button></div>
 {tab==='ia'&&<><div className="card"><h3>Personalidad</h3><div className="chips">{Object.entries(personas).map(([k,v])=><button key={k} className={persona.persona===k?'chip active':'chip'} onClick={async()=>{const n={...persona,persona:k};setPersona(n);await savePersona(k as any,n.intensity)}}>{v as string}</button>)}</div><label className="switchrow"><span>Intensidad {persona.intensity}/5</span><input type="range" min="1" max="5" value={persona.intensity} onChange={async e=>{const n={...persona,intensity:Number(e.target.value)};setPersona(n);await savePersona(n.persona,n.intensity)}}/></label></div><div className="card"><h3>IA proactiva</h3><label className="switchrow"><span>Activar recomendaciones</span><input type="checkbox" checked={!!pro?.enabled} onChange={async e=>{const n={...pro,enabled:e.target.checked};setPro(n);await saveProactiveSettings(n)}}/></label><div className="inline"><select value={pro?.frequency||'daily'} onChange={async e=>{const n={...pro,frequency:e.target.value};setPro(n);await saveProactiveSettings(n)}}><option value="low">Baja</option><option value="daily">Diaria</option><option value="high">Alta</option></select><select value={pro?.interruption||'normal'} onChange={async e=>{const n={...pro,interruption:e.target.value};setPro(n);await saveProactiveSettings(n)}}><option value="quiet">Solo silenciosas</option><option value="normal">Normal</option><option value="important_only">Solo importantes</option></select></div><button className="primary full" disabled={busy||!pro?.enabled} onClick={refresh}>Analizar ahora</button></div>{events.map(e=><div className="card" key={e.id}><b>{e.title}</b><p>{e.body}</p><button className="ghost" onClick={async()=>{await dismissProactive(e.id);setEvents(events.filter(x=>x.id!==e.id))}}>Descartar</button></div>)}</>}
 {tab==='food'&&<><div className="card"><h3>Planificación alimentaria</h3><p className="muted">Plan simple de 7 días. La IA podrá personalizarlo con tus objetivos y registros.</p><button className="primary full" disabled={busy} onClick={makePlan}>Crear plan semanal</button></div>{plans.map(p=><div className="card" key={p.id}><h3>{p.name}</h3>{(p.meal_plan_items||[]).slice(0,8).map((x:any)=><label className="switchrow" key={x.id}><span>{x.date} · {x.title}</span><input type="checkbox" checked={x.completed} onChange={async e=>{await completeMealItem(x.id,e.target.checked);setPlans(await getMealPlans())}}/></label>)}</div>)}</>}
 {tab==='game'&&<div className="card"><h3>Progreso sin exceso de gamificación</h3><p className="muted">La Fase 5 agrega hitos y logros como refuerzo, sin convertir Impulse en un juego.</p><div className="milestone">🔥 Consistencia · registrá hábitos varios días seguidos</div><div className="milestone">🎯 Objetivo · completá un objetivo</div><div className="milestone">📈 Mejora · mantené una tendencia positiva</div></div>}
 {tab==='premium'&&<div className="card"><h3>Premium</h3><p className="muted">RevenueCat queda preparado para activar compras reales. No se cobra automáticamente desde esta fase.</p><button className="primary full" onClick={async()=>alert((await refreshSubscriptionFromStore())?'Premium activo en la tienda':'No hay entitlement Premium activo')}>Comprobar suscripción</button></div>}
 </div></div>}
